name: dash_pdf
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter_svg: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  file_picker: ^8.0.0
  flutter_cache_manager: ^3.3.1
  pdf: ^3.10.8
  fluttertoast: ^8.0.8
  flutter_image_compress: ^2.2.0

  ffi: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/dark/header.svg
    - assets/images/dark/compress.png
